// Generated by https://quicktype.io

export interface User {
    _id:            string;
    sonidero_name:  string;
    avatar:         string;
    email:          string;
    associated_acc: string;
    createdAt:      string;
    updatedAt:      string;
    __v:            number;
    token:          Token;
}

export interface Token {
    accessToken: string;
}
